spring.application.name=Orders

server.port=8086

services.wallet.url=http://localhost:8083
services.portfolio.url=http://localhost:8084

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:public-key.pem