spring.application.name=ScreenerModule

server.port=8089

services.instrument.url=http://instrument-service:8085
services.company-data.url=http://company-data-service:8087
services.price-history.url=http://price-history-service:8088

