spring.application.name=ScreenerModule

server.port=8089

services.instrument.url=http://localhost:8085
services.company-data.url=http://localhost:8087
services.price-history.url=http://localhost:8088

